### ISSUE TITLE
Manuscript link does not work.

### ISSUE THREAD

**Issue by andrewrech** [RhoInc/datadigest#38]

**Comment by jwildfire** [comment]
Thanks for the issue, @andrewrech.

The [manuscript link](https://phusewiki.org/docs/2018_US%20Connect18/DV%20STREAM/dv12%20final.pdf) was working for me, but the vignette link was old so we fixed that (Correct link [here](https://cran.r-project.org/web/packages/datadigest/vignettes/datadigest.html)) in the readme and wiki. If the manuscript link is down for you, let us know which browser you're in. Let us know if there is anything else!
